# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.14

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/core/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.6707.69/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/core/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.6707.69/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/core/Desktop/pvpgn-server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/core/Desktop/pvpgn-server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/core/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.6707.69/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/home/core/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.6707.69/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/core/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.6707.69/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/home/core/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.6707.69/bin/cmake/linux/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/core/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.6707.69/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/core/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.6707.69/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/home/core/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.6707.69/bin/cmake/linux/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/home/core/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.6707.69/bin/cmake/linux/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/core/.local/share/JetBrains/Toolbox/apps/CLion/ch-0/191.6707.69/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/core/Desktop/pvpgn-server/CMakeFiles /home/core/Desktop/pvpgn-server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/core/Desktop/pvpgn-server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f CMakeFiles/uninstall.dir/build.make CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named purge

# Build rule for target.
purge: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 purge
.PHONY : purge

# fast build rule for target.
purge/fast:
	$(MAKE) -f CMakeFiles/purge.dir/build.make CMakeFiles/purge.dir/build
.PHONY : purge/fast

#=============================================================================
# Target rules for targets named compat

# Build rule for target.
compat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 compat
.PHONY : compat

# fast build rule for target.
compat/fast:
	$(MAKE) -f src/compat/CMakeFiles/compat.dir/build.make src/compat/CMakeFiles/compat.dir/build
.PHONY : compat/fast

#=============================================================================
# Target rules for targets named common

# Build rule for target.
common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 common
.PHONY : common

# fast build rule for target.
common/fast:
	$(MAKE) -f src/common/CMakeFiles/common.dir/build.make src/common/CMakeFiles/common.dir/build
.PHONY : common/fast

#=============================================================================
# Target rules for targets named win32

# Build rule for target.
win32: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 win32
.PHONY : win32

# fast build rule for target.
win32/fast:
	$(MAKE) -f src/win32/CMakeFiles/win32.dir/build.make src/win32/CMakeFiles/win32.dir/build
.PHONY : win32/fast

#=============================================================================
# Target rules for targets named bntrackd

# Build rule for target.
bntrackd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bntrackd
.PHONY : bntrackd

# fast build rule for target.
bntrackd/fast:
	$(MAKE) -f src/bntrackd/CMakeFiles/bntrackd.dir/build.make src/bntrackd/CMakeFiles/bntrackd.dir/build
.PHONY : bntrackd/fast

#=============================================================================
# Target rules for targets named bnchat

# Build rule for target.
bnchat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bnchat
.PHONY : bnchat

# fast build rule for target.
bnchat/fast:
	$(MAKE) -f src/client/CMakeFiles/bnchat.dir/build.make src/client/CMakeFiles/bnchat.dir/build
.PHONY : bnchat/fast

#=============================================================================
# Target rules for targets named bnftp

# Build rule for target.
bnftp: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bnftp
.PHONY : bnftp

# fast build rule for target.
bnftp/fast:
	$(MAKE) -f src/client/CMakeFiles/bnftp.dir/build.make src/client/CMakeFiles/bnftp.dir/build
.PHONY : bnftp/fast

#=============================================================================
# Target rules for targets named bnbot

# Build rule for target.
bnbot: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bnbot
.PHONY : bnbot

# fast build rule for target.
bnbot/fast:
	$(MAKE) -f src/client/CMakeFiles/bnbot.dir/build.make src/client/CMakeFiles/bnbot.dir/build
.PHONY : bnbot/fast

#=============================================================================
# Target rules for targets named bnstat

# Build rule for target.
bnstat: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bnstat
.PHONY : bnstat

# fast build rule for target.
bnstat/fast:
	$(MAKE) -f src/client/CMakeFiles/bnstat.dir/build.make src/client/CMakeFiles/bnstat.dir/build
.PHONY : bnstat/fast

#=============================================================================
# Target rules for targets named bni2tga

# Build rule for target.
bni2tga: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bni2tga
.PHONY : bni2tga

# fast build rule for target.
bni2tga/fast:
	$(MAKE) -f src/bniutils/CMakeFiles/bni2tga.dir/build.make src/bniutils/CMakeFiles/bni2tga.dir/build
.PHONY : bni2tga/fast

#=============================================================================
# Target rules for targets named bnibuild

# Build rule for target.
bnibuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bnibuild
.PHONY : bnibuild

# fast build rule for target.
bnibuild/fast:
	$(MAKE) -f src/bniutils/CMakeFiles/bnibuild.dir/build.make src/bniutils/CMakeFiles/bnibuild.dir/build
.PHONY : bnibuild/fast

#=============================================================================
# Target rules for targets named tgainfo

# Build rule for target.
tgainfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tgainfo
.PHONY : tgainfo

# fast build rule for target.
tgainfo/fast:
	$(MAKE) -f src/bniutils/CMakeFiles/tgainfo.dir/build.make src/bniutils/CMakeFiles/tgainfo.dir/build
.PHONY : tgainfo/fast

#=============================================================================
# Target rules for targets named bnilist

# Build rule for target.
bnilist: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bnilist
.PHONY : bnilist

# fast build rule for target.
bnilist/fast:
	$(MAKE) -f src/bniutils/CMakeFiles/bnilist.dir/build.make src/bniutils/CMakeFiles/bnilist.dir/build
.PHONY : bnilist/fast

#=============================================================================
# Target rules for targets named bniextract

# Build rule for target.
bniextract: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bniextract
.PHONY : bniextract

# fast build rule for target.
bniextract/fast:
	$(MAKE) -f src/bniutils/CMakeFiles/bniextract.dir/build.make src/bniutils/CMakeFiles/bniextract.dir/build
.PHONY : bniextract/fast

#=============================================================================
# Target rules for targets named sha1hash

# Build rule for target.
sha1hash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sha1hash
.PHONY : sha1hash

# fast build rule for target.
sha1hash/fast:
	$(MAKE) -f src/bnpass/CMakeFiles/sha1hash.dir/build.make src/bnpass/CMakeFiles/sha1hash.dir/build
.PHONY : sha1hash/fast

#=============================================================================
# Target rules for targets named bnpass

# Build rule for target.
bnpass: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bnpass
.PHONY : bnpass

# fast build rule for target.
bnpass/fast:
	$(MAKE) -f src/bnpass/CMakeFiles/bnpass.dir/build.make src/bnpass/CMakeFiles/bnpass.dir/build
.PHONY : bnpass/fast

#=============================================================================
# Target rules for targets named bnetd

# Build rule for target.
bnetd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bnetd
.PHONY : bnetd

# fast build rule for target.
bnetd/fast:
	$(MAKE) -f src/bnetd/CMakeFiles/bnetd.dir/build.make src/bnetd/CMakeFiles/bnetd.dir/build
.PHONY : bnetd/fast

#=============================================================================
# Target rules for targets named d2cs

# Build rule for target.
d2cs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 d2cs
.PHONY : d2cs

# fast build rule for target.
d2cs/fast:
	$(MAKE) -f src/d2cs/CMakeFiles/d2cs.dir/build.make src/d2cs/CMakeFiles/d2cs.dir/build
.PHONY : d2cs/fast

#=============================================================================
# Target rules for targets named d2dbs

# Build rule for target.
d2dbs: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 d2dbs
.PHONY : d2dbs

# fast build rule for target.
d2dbs/fast:
	$(MAKE) -f src/d2dbs/CMakeFiles/d2dbs.dir/build.make src/d2dbs/CMakeFiles/d2dbs.dir/build
.PHONY : d2dbs/fast

#=============================================================================
# Target rules for targets named bigint

# Build rule for target.
bigint: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bigint
.PHONY : bigint

# fast build rule for target.
bigint/fast:
	$(MAKE) -f src/test/CMakeFiles/bigint.dir/build.make src/test/CMakeFiles/bigint.dir/build
.PHONY : bigint/fast

#=============================================================================
# Target rules for targets named bnetsrp3_test

# Build rule for target.
bnetsrp3_test: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bnetsrp3_test
.PHONY : bnetsrp3_test

# fast build rule for target.
bnetsrp3_test/fast:
	$(MAKE) -f src/test/CMakeFiles/bnetsrp3_test.dir/build.make src/test/CMakeFiles/bnetsrp3_test.dir/build
.PHONY : bnetsrp3_test/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install"
	@echo "... edit_cache"
	@echo "... uninstall"
	@echo "... install/local"
	@echo "... test"
	@echo "... list_install_components"
	@echo "... purge"
	@echo "... rebuild_cache"
	@echo "... compat"
	@echo "... common"
	@echo "... win32"
	@echo "... bntrackd"
	@echo "... bnchat"
	@echo "... bnftp"
	@echo "... bnbot"
	@echo "... bnstat"
	@echo "... bni2tga"
	@echo "... bnibuild"
	@echo "... tgainfo"
	@echo "... bnilist"
	@echo "... bniextract"
	@echo "... sha1hash"
	@echo "... bnpass"
	@echo "... bnetd"
	@echo "... d2cs"
	@echo "... d2dbs"
	@echo "... bigint"
	@echo "... bnetsrp3_test"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

